### ISSUE TITLE
Character sprite

### ISSUE THREAD

**Issue by ThibManfredi** [l3mpire/lemverse#22]
Hello ! 

We use characters sprite from itch.io, and we have to cut evey characters files in order to make them compatible to lemverse,

Do you have any tips in order to make this process a little bit less time consuming ?

A sprite base when we deploy lemverse regarding characters could be a good idea for next maj and improvments :)

**Comment by Donorhan** [comment]
Personally I find that Phaser handles animations and Sprites very badly, having a Sprite that has animations seems absurd to me. An animation should be totally uncorrelated with a sprite, in the end it's just a matter of moving a rectangle on an image, no matter the image. This is the first problematic point for me.

The second point is the current management of the characters, we load the characters by layers. So we have one sprite per layer (and therefore one animation per layer). This is problematic for two reasons:
- in terms of performance, we have 5 draw calls per character (and no batching possible because they are different textures)
- a lot of texture loading (for each layer we load all the elements available in memory for it)

### Solutions
For the sprite management the idea would be to have only animations names in the code (run_up, run_left, ...) without knowing anything about sprites (thanks to sprite atlas), the animations would be in JSON files outside the sprites to be reusable


Concerning the images, we should set up an API (with a tool like [IMGPROXY](https://imgproxy.net) would be great). The idea would be to distribute live the images for the characters with a URL like `/api/character?body=[id]&clothes=[id]&hairs=[id]`. The server would assemble the images in order to generate a single one which would then be cached to avoid being rebuilt each time. With this we would have at most one image to load per character and also allow new things like changing the colors of the characters in live.

For now we could possibly create a simple script to generate an image in the right format from individual character images but that would require a lot of development for a temporary problem :/

**Comment by riderx** [comment]
@Donorhan the unique url path look promising !
image magic can do the work you think ?

**Comment by Donorhan** [comment]
Yes image magic should be enough for that :)

**Comment by riderx** [comment]
@Donorhan i found the way to merge the image with gm
```
const gm = require('gm')

const w = 384;
const h = 128;
const body = "/Users/martindonadieu/Downloads/lemlist_lemverse_tilesset/copr.png"
const clothes = "/Users/martindonadieu/Downloads/lemlist_lemverse_tilesset/clothe_12.png"
const hairs = "/Users/martindonadieu/Downloads/lemlist_lemverse_tilesset/head_1.png"
const eyes = "/Users/martindonadieu/Downloads/lemlist_lemverse_tilesset/glasse.png.png"
const accessory = "/Users/martindonadieu/Downloads/lemlist_lemverse_tilesset/acc17.png"
const result = "/Users/martindonadieu/Downloads/lemlist_lemverse_tilesset/merged.png"


img = gm(w, h);
img.in(body)
.in(clothes)
.in('-geometry', "+0+0")
.in('-page', "+0+0")
.in(hairs)
.in('-geometry', "+0+0")
.in('-page', "+0+0")
.in(eyes)
.in('-geometry', "+0+0")
.in('-page', "+0+0")
.in(accessory)
.in('-geometry', "+0+0")
.in('-page', "+0+0")
.mosaic()
.write(result, (err) => {
    if (!err) console.log('done');
    else console.log(err);
});
```
But I have no idea of how create API endpoint in meteor.
I will continue to investigate later

**Comment by riderx** [comment]
@Donorhan your last change fix the itch issue i think it can be close

**Comment by Donorhan** [comment]
Indeed, thank you!
