### ISSUE TITLE
Is mup necessary inside repo ?

### ISSUE THREAD

**Issue by riderx** [l3mpire/lemverse#3]
I can see on the source you use MUP with some improvement for lempire.

I was wandering why not create a repo for it, like a fork of mup, and do `npm i -g https://github.com/l3mpire/mup`

It will keep lempire smaller and allow people to use your fork, and let you get the lasted patch from the original team easily with a github action.

**Comment by riderx** [comment]
For docker build i totally ignored the mup folder, do i miss something about it or I can go without it ?

**Comment by DblK** [comment]
For the MUP folder inside docker there is no need, so that is perfect.
For creating a new repository for our version of mup, we currently have a monorepo so we won't make the effort to make a separate one as the one contained in this repo is slightly different from the one in our monorepo 😉 .

So no plan for now to move it away ^^
