### ISSUE TITLE
Can't run on Apple M1

### ISSUE THREAD

**Issue by ramnes** [l3mpire/lemverse#53]
Lemverse depends on `fourseven:scss`, that depends on `node-sass`, that doesn't seem to be available for the Darwin ARM platform. `public/app/bin/run` gives:

```
=> Errors prevented startup:

   While loading package fourseven:scss@4.15.0:
   error: Command failed: /Users/ramnes/.meteor/packages/meteor-tool/.2.7.3.1liadnk.e36f++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin/npm rebuild --update-binary
   Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/darwin-arm64-83_binding.node":

   HTTP error 404 Not Found
```

**Comment by xsyann** [comment]
I ran into the same issue with Apple M1 chip and solved it using instructions found here: https://forums.meteor.com/t/fourseven-scss-package-problem-during-installation-node-sass-on-macos/58002/8

1. Using node 14.20.0 (`nvm use 14`)
2. Installing meteor using npm instead of curl (`npm install -g meteor`)

**Comment by ramnes** [comment]
It's weird that depending on how you installed Meteor you get this error or not... but yes, it works. :)

Thanks!

**Comment by ramnes** [comment]
I've just hit this issue again with meteor 2.12. Downgrading to meteor 2.9 fixed it.
