### ISSUE TITLE
Incorrect tiles being placed

### ISSUE THREAD

**Issue by ramnes** [l3mpire/lemverse#82]
https://user-images.githubusercontent.com/835072/185372791-573069a9-3012-4011-98c7-9dc1b5328693.mov

**Comment by Donorhan** [comment]
This bug is present when your tileset has the same firstgid as another tileset.

I've seen that when uploading a tileset we set the attribut `firstgid` according the previous tileset `firstgid`. The upload of a tileset is asynchronous so I think the server must assign a wrong firstgid when several images are dragged at the same time, a race condition problem I think

**Comment by alimtunc** [comment]
> This bug is present when your tileset has the same firstgid as another tileset.
> 
> I've seen that when uploading a tileset we set the attribut `firstgid` according the previous tileset `firstgid`. The upload of a tileset is asynchronous so I think the server must assign a wrong firstgid when several images are dragged at the same time, a race condition problem I think

Hi Dono, you were right. The problem comes from the `gid` setted on `files.js -> line 36`. The asynchronous insert, breaking this `maxTilesetGid` logic and setting the same gid for some tilesets.

The solution would be to make the upload synchronously to not miss the last gid. But maybe we could generate this gid ? I don't really get it for you using it, as I see you using it for iterations at some place, but I didn't get the end point of this.

Maybe you have a better suggestion to fix this ? :)

**Comment by Donorhan** [comment]
This is useful for Phaser to know which tileset it should use, for example if we have :
- Tileset A : gid = 0
- Tileset B : gid = 10000
- Tileset C : gid = 20000

If we want to draw a tile with id 15000, Phaser knows that it must use tileset B.

From what I saw in Phaser's code, it generates a huge array from 0 to max gid + tileset's tile count, so it's hard to generate automatically. The current system limits the number of tiles per Tileset to 10000 (that leaves room for images up to 1600x1600 pixels).

So for the moment, apart from a better management of the asynchronous upload, I don't see many solutions to fix this 😕

**Comment by alimtunc** [comment]
What do you think by this solution @Donorhan : 
 - Uploading all files asynchronously but not inserting the Tiles directly
 - Fetching `fileRefs` with an event like `afterAllUpload`
 - Iterate this array of `fileRefs` and insert synchronously the Tiles, while saving the `gid` to iterate
 
This is the only way I see to keep the last `gid` that we can Iterate

**Comment by Donorhan** [comment]
@alimtunc By Tiles you mean Tileset? Sounds good to me 🙂

**Comment by alimtunc** [comment]
> @alimtunc By Tiles you mean Tileset? Sounds good to me 🙂

I founded a better solutions while keeping all asynchronously !

If you wanna check it, you can here https://github.com/Refty/lemverse/pull/7/files 

I'm just adding the `gid` on the files and getting it back with the fileref while inserting tilesets

![Capture d’écran 2022-08-24 à 16 45 55](https://user-images.githubusercontent.com/18298759/186448978-98ca9881-8852-4d9c-b911-a07eab6136d0.png)
